language: R
sudo: required
cache: packages

r_packages:
  - bookdown

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_installPandoc.sh

before_install:
  - tlmgr install xcolor sectsty babel babel-norsk framed libertine mweights fontaxes epigraph

script:
  - ./_installPandoc.sh
  - ./_build.sh

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master
    type: push

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
