
# fraSted {-}

| | |
|----|----|
| Navn     | fraSted |
| Label    | , Fra sted (NPK) |
| Type     | Integer, String |
| Length   | 8, 2, 30    |
| Format   | , FRASTED |
| Kilde    |   |

**Finnes i filene**

SKDE19.T19_EXTRA_AVTSPES_2014, SKDE19.T19_EXTRA_AVTSPES_2015, SKDE19.T19_EXTRA_AVTSPES_2016, SKDE19.T19_EXTRA_AVTSPES_2017, SKDE19.T19_EXTRA_AVTSPES_2018, SKDE19.T19_PARVUS_AVD_2014, SKDE19.T19_PARVUS_AVD_2015, SKDE19.T19_PARVUS_AVD_2016, SKDE19.T19_PARVUS_AVD_2017, SKDE19.T19_PARVUS_AVD_2018, SKDE19.T19_PARVUS_AVTSPES_2014, SKDE19.T19_PARVUS_AVTSPES_2015, SKDE19.T19_PARVUS_AVTSPES_2016, SKDE19.T19_PARVUS_AVTSPES_2017, SKDE19.T19_PARVUS_AVTSPES_2018, SKDE19.T19_PARVUS_SHO_2014, SKDE19.T19_PARVUS_SHO_2015, SKDE19.T19_PARVUS_SHO_2016, SKDE19.T19_PARVUS_SHO_2017, SKDE19.T19_PARVUS_SHO_2018, SKDE19.T19_REHAB_2014_18, NPR19.M19_AVD1418_UTLEVERINGSFIL, NPR19.M19_AVD2014_UTLEVERINGSFIL, NPR19.M19_AVD2015_UTLEVERINGSFIL, NPR19.M19_AVD2016_UTLEVERINGSFIL, NPR19.M19_AVD2017_UTLEVERINGSFIL, NPR19.M19_AVD2018_UTLEVERINGSFIL, NPR19.M19_AVTSPESSOM1418_UTL_FIL, NPR19.M19_AVTSPESSOM2014_UTL_FIL, NPR19.M19_AVTSPESSOM2015_UTL_FIL, NPR19.M19_AVTSPESSOM2016_UTL_FIL, NPR19.M19_AVTSPESSOM2017_UTL_FIL, NPR19.M19_AVTSPESSOM2018_UTL_FIL, NPR19.M19_DIALYSE1618_UTL_FIL, NPR19.M19_LEGEMIDLER1418_UTL_FIL, NPR19.M19_REHAB1418_UTL_FIL, NPR19.M19_SHO1418_UTLEVERINGSFIL, NPR19.M19_SHO2014_UTLEVERINGSFIL, NPR19.M19_SHO2015_UTLEVERINGSFIL, NPR19.M19_SHO2016_UTLEVERINGSFIL, NPR19.M19_SHO2017_UTLEVERINGSFIL, NPR19.M19_SHO2018_UTLEVERINGSFIL, NPR19.M19_SYKEHUS1418_UTL_FIL

